name:Hello World

on: push

jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/Checkout@v4
        - name: Echo Text
          run: echo "Hello, World"
