name: Multiple Jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y
            - name: Execute Cowsay CDM
              run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
            - name: Sleep for 30 seconds
              run: sleep 30
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
          - name: Sleep for 10 Seconds
            run: slepp 10
          - name: Test File exists
            run: grep -i "dargon" dragon.txt
    deploy_job_3:
        needs: [build_job_1, test_job_2]
        runs-on: ubuntu-latest
        steps:
            - name: Read File
              run: cat dragon.txt
            - name: Deploy
              run: echo Deploying ... ...

